[features]
seeds = false
skip-lint = false
[programs.localnet]
nexuz = "6C5Mf4sDpFzhNbrZtMf1b4RFLbnAzUdZ9C86cz2MZPh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/var/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
